language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "pip install flake8"
  - "pip install -r requirements.txt"
before_script: "flake8 ."
script: "py.test -v --driver Firefox --variables variables.json tests"
notifications:
  email: false
